apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - image: cmandolk.azurecr.io/vote:193
        name: vote
        ports:
        - containerPort: 80
          name: vote
